version: '3'
services:
  yuzu:
    tty: true
    image: yuzu/emulator:latest
    container_name: yuzu
    privileged: true
    volumes:
      - "./:/workspace"
      - "~/.Xauthority:/root/.Xauthority"
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    command: bash